version: '3'

services:
  fastapi:
    build:
      context: ./
      dockerfile: fastapi.Dockerfile
    ports:
      - "8001:8001"
    networks:
      - app-network

  locust:
    build:
      context: ./
      dockerfile: locust.Dockerfile
    ports:
      - "8089:8089"
    depends_on:
      - fastapi
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
